# Generated by Django 4.2.8 on 2023-12-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_software_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareversion',
            old_name='default_action',
            new_name='software_version_type',
        ),
        migrations.AddField(
            model_name='softwareversion',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='softwareversion',
            name='software_hash_value',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.DeleteModel(
            name='SoftwareVersionRule',
        ),
    ]
